[package]
name = "rget"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
reqwest = { version = "0.12.5", features = ["stream"] }
tokio = { version = "1.39.2", features = ["full"] }
