[package]
name = "rget"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
futures = "0.3.30"
http = "1.1.0"
reqwest = { version = "0.12.5", features = ["stream"] }
tokio = { version = "1.39.2", features = ["full", "rt", "rt-multi-thread"] }
